version : '3'
services :
  db:
    image: bitnami/postgresql:11-debian-9
    container_name: doggy_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=doggy
      - POSTGRES_PASSWORD=skool
      - POSTGRES_DB=doggy
      - DB_USER=
      - PGPASSWORD=nopwd
