spring:
  datasource:
    #url: "jdbc:postgresql://localhost/doggy"
    url: "jdbc:postgresql://db/doggy"
    username: "doggy"
    password: "skool"
server:
  port: 8080

# Swagger
springfox:
  documentation:
    swagger:
      v2:
        path: /docs/api-docs.json