# Values here are used as default, as long as they are not overridden in an external file loaded with --spring.config.location
# See common-application-properties in https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# All properties starting with "ENC()" are encrypted properties. See readme to encrypt or decrypt them
# Configuration for actuator endpoints
management:
  server:
    port: 8090
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      path-mapping:
        info: info
        health: actuator/health
        metrics: actuator/metrics
        prometheus: actuator/prometheus
      base-path: /
  info:
    git:
      mode: FULL
spring:
  datasource:
    #url: "jdbc:postgresql://localhost/doggy"
    url: "jdbc:postgresql://db/doggy"
    username: "doggy"
    password: "skool"
server:
  port: 8080
  tomcat:
    max-connections: 10000 # Maximum number of connections that the server accepts and processes at any given time.
    max-threads: 200 # Maximum amount of worker threads.
    accept-count: 0 # Maximum queue length for incoming connection requests when all possible request processing threads are in use.
    basedir: "."
    accesslog:
      enabled: true
      buffered: false
      rotate: true
      request-attributes-enabled: false # Set request attributes for the IP address, Hostname, protocol, and port used for the request.
      prefix: "access_log."
      suffix: ".log"
      file-date-format: "yyyy-MM-dd"
      pattern: "%t %r - %s %D %I %{x-traceid}i"

# Swagger
springfox:
  documentation:
    swagger:
      v2:
        path: /docs/api-docs.json