INSERT INTO doggies VALUES ('BRM', 'Martins', 'Brandone',  'Brondon', 'https://firebasestorage.googleapis.com/v0/b/doggy-chat.appspot.com/o/doggy-photos%2Fbrm.jpg?alt=media&token=f25980ed-b9fd-451e-90e3-3eed64989de7', 'WEBF', 'rit très fort');
INSERT INTO doggies VALUES ('RDO', 'Dormoy', 'Remi',  'Rémido', 'https://firebasestorage.googleapis.com/v0/b/doggy-chat.appspot.com/o/2019-09-26T12%3A57%3A47.835Zyolo?alt=media&token=246f6e8f-2fa0-4974-baa3-2c63b5d75e69', 'CONEX', 'boit du Ricard');
INSERT INTO doggies VALUES ('BEJ', 'Jarlier', 'Benoit',  'Bénoit', 'https://firebasestorage.googleapis.com/v0/b/doggy-chat.appspot.com/o/doggy-photos%2Fbej.jpg?alt=media&token=821ad501-21f1-4250-9480-b32dec5b64a8', 'NAD', 'boit beaucoup');
INSERT INTO doggies VALUES ('LAAL','Lambert' , 'Alizée',  'Alizouz', 'https://firebasestorage.googleapis.com/v0/b/doggy-chat.appspot.com/o/doggy-photos%2Falizee.jpg?alt=media&token=8aedd71b-73e7-4bfb-bcf3-af4ef1049155', 'UX', 'voit le bon côté des choses');
INSERT INTO doggies VALUES ('DAS', 'Sala', 'Daniel',  'Daniboy', 'https://firebasestorage.googleapis.com/v0/b/doggy-chat.appspot.com/o/doggy-photos%2Fdanyboy.jpg?alt=media&token=02490ee8-94a8-4385-8a1c-8d56a7aa187a', 'SCALE', 'a le plus beau boule du monde');
INSERT INTO doggies VALUES ('MBI', 'Biardeau', 'Marie',  'Marizouz', 'https://firebasestorage.googleapis.com/v0/b/doggy-chat.appspot.com/o/doggy-photos%2Fmarie.jpg?alt=media&token=e89b9025-35f3-40df-b6a0-3073b4372fe0', 'OCAC', 'boit des shots');
INSERT INTO doggies VALUES ('JDO', 'Dompe', 'Juliette',  'Juju', 'https://firebasestorage.googleapis.com/v0/b/doggy-chat.appspot.com/o/doggy-photos%2Fjuliette.jpg?alt=media&token=6abf4e32-73e2-46e2-813b-79f0c454bb07', 'ARCHI', 'fait des cocktails');
INSERT INTO doggies VALUES ('BME', 'Meriaux', 'Benoit',  'Renoit', 'https://firebasestorage.googleapis.com/v0/b/doggy-chat.appspot.com/o/doggy-photos%2Fbme.jpg?alt=media&token=2bd7adbd-a886-42a4-bcea-e41bdf69f49d', 'NAD', 'court très vite');
INSERT INTO doggies VALUES ('FAM', 'Massin', 'Faustine',  'le bateau ', 'https://firebasestorage.googleapis.com/v0/b/doggy-chat.appspot.com/o/doggy-photos%2Ffaustine.jpg?alt=media&token=f4909448-49cb-49cc-8e5f-d273cb927819', 'NAD', 'parle beaucoup de sexe');
INSERT INTO doggies VALUES ('CLI', 'Liu', 'Can', 'Can', 'https://firebasestorage.googleapis.com/v0/b/doggy-chat.appspot.com/o/doggy-photos%2Fcan.jpg?alt=media&token=4d648e28-ba9d-4cf9-a176-f34ce1f83a36', 'ARCHI', 'sait bien faire vibrer ses fesses');
INSERT INTO doggies VALUES ('CEM', 'Martin', 'Cedric',  'Cédric', 'https://firebasestorage.googleapis.com/v0/b/doggy-chat.appspot.com/o/doggy-photos%2Fcem.jpg?alt=media&token=ec8eefc5-8c8e-4ceb-bdff-8c7540084cab', 'NAD', 'maîtrise l''art de maîtriser');
INSERT INTO doggies VALUES ('CYG', 'Guegan', 'Cyril',  'Cygounette', 'https://firebasestorage.googleapis.com/v0/b/doggy-chat.appspot.com/o/doggy-photos%2Fcyril.jpg?alt=media&token=2a26a82e-46af-4c06-8269-aa88285b4481', 'ARCHI', 'Met des grandes claques dans le dos');
INSERT INTO doggies VALUES ('MEG', 'Menanteau', 'Mégane',  'Megazouz', 'https://firebasestorage.googleapis.com/v0/b/doggy-chat.appspot.com/o/doggy-photos%2Fmegane.jpg?alt=media&token=d473bbb5-b521-41ff-8e0a-a454865a547d', 'WEBF', 'C''est une chaudière');
INSERT INTO doggies VALUES ('JORO','Robert' , 'Joseph',  'JOROOOOO', 'https://firebasestorage.googleapis.com/v0/b/doggy-chat.appspot.com/o/doggy-photos%2Fjoseph.jpg?alt=media&token=82961ccf-3774-49c3-9476-cc769db5a723', 'ARCHI', 'Court très vite');
INSERT INTO doggies VALUES ('LJA', 'Jacquemin', 'Leo',  'Léo', 'https://firebasestorage.googleapis.com/v0/b/doggy-chat.appspot.com/o/doggy-photos%2Fleo.jpg?alt=media&token=b6b16194-c0a5-4d7e-9bc5-feccaba555fc', 'WEBF', 'fait des dry january indéfiniment');
INSERT INTO doggies VALUES ('MID', 'Durdevic', 'Mila',  'Mila', 'https://firebasestorage.googleapis.com/v0/b/doggy-chat.appspot.com/o/doggy-photos%2Fmila.jpg?alt=media&token=25b68c44-a34e-4536-a554-7f6c284e6324', 'CRAFT', 'Prend une grande caisse par an');
INSERT INTO doggies VALUES ('SLU', 'Lundy', 'Stéphane', 'Le Mondai', 'https://firebasestorage.googleapis.com/v0/b/doggy-chat.appspot.com/o/doggy-photos%2Fslu.jpg?alt=media&token=527e368e-75ec-413c-bdb5-1d8fc8482e9a', 'Autres', 'Maîtrise le feu');
INSERT INTO doggies VALUES ('RBO', 'Botter', 'Rafaëlle', 'Le fantôme', 'https://firebasestorage.googleapis.com/v0/b/doggy-chat.appspot.com/o/doggy-photos%2Frafaelle.jpg?alt=media&token=d361b266-d31d-49d2-b682-52e9c2ba091f', 'Autres', 'parle beaucoup trop');

INSERT INTO defis(id, citation) VALUES ( 1, "Blague zoophile ? C'est un mec qui rentre dans un bar ...")
INSERT INTO defis(id, citation) VALUES ( 2, "Blague zoophile ? C'est un mec qui prend son élan ...")
INSERT INTO defis(id, citation) VALUES ( 3, "Y a 5 places dans une Mégane.")
INSERT INTO defis(id, citation) VALUES ( 4, "Salto cul nu !")
INSERT INTO defis(id, citation) VALUES ( 5, "Il est ricard moins l'quart.")
INSERT INTO defis(id, citation) VALUES ( 6, "Problème de chaudière ...")
INSERT INTO defis(id, citation) VALUES ( 7, "Moi le matin je n'enfile pas que des pantoufles")
INSERT INTO defis(id, citation) VALUES ( 8, "Je fais beaucoup d'oral.")
INSERT INTO defis(id, citation) VALUES ( 9, "Pépite !")
INSERT INTO defis(id, citation) VALUES ( 10, "Le vrai nom de PANDA, c'est la ligue MOA.")
INSERT INTO defis(id, citation) VALUES ( 11, "Arrêtez de me limer !")
INSERT INTO defis(id, citation) VALUES ( 12, "Nom de Zeus !")
INSERT INTO defis(id, citation) VALUES ( 13, "Rio, à Barra Club, l'autoroute du cul je te dis !")
INSERT INTO defis(id, citation) VALUES ( 14, "Missile !")
INSERT INTO defis(id, citation) VALUES ( 15, "Tout en alcoolisme ...")
INSERT INTO defis(id, citation) VALUES ( 16, "Carton !")
INSERT INTO defis(id, citation) VALUES ( 17, "Bolide !")
INSERT INTO defis(id, citation) VALUES ( 18, "Tu passeras dans mon bureau que je te rapelle les valeurs de la team Jachère.")
INSERT INTO defis(id, citation) VALUES ( 19, "Et ce soir ... on baise !")
INSERT INTO defis(id, citation) VALUES ( 20, "OOOOOUUuuuuuwwwAAAAAAAAAAAAAAA")
INSERT INTO defis(id, citation) VALUES ( 21, "J'en veux Jooooooooooe !")
INSERT INTO defis(id, citation) VALUES ( 22, "Combien tu mesures ???? ... Jamais vu un tas de merde aussi haut !")
INSERT INTO defis(id, citation) VALUES ( 23, "C'est ça que j'aime bien chez toi ... !")
INSERT INTO defis(id, citation) VALUES ( 24, "Comme elle est belle !")
INSERT INTO defis(id, citation) VALUES ( 25, "J'étais à 2 doigts de mettre le 3ème")
INSERT INTO defis(id, citation) VALUES ( 26, "Molo, on a dit !")
INSERT INTO defis(id, citation) VALUES ( 27, "J'ai envie de tout casser.")
INSERT INTO defis(id, citation) VALUES ( 28, "Allez ! Ciao les cons !")
INSERT INTO defis(id, citation) VALUES ( 29, "Le barman, il s'appelait Ivan ... Ivan Aboire")
INSERT INTO defis(id, citation) VALUES ( 30, "Et puis une enquête ça fera pas de mal non plus ! Qu'on nettoie un peu OCTO !")
INSERT INTO defis(id, citation) VALUES ( 31, "Les meufs, tu leurs parles ... et elles répondent !")
INSERT INTO defis(id, citation) VALUES ( 32, "Mais téma wesh !")
INSERT INTO defis(id, citation) VALUES ( 33, "Ah !")
INSERT INTO defis(id, citation) VALUES ( 34, "C'est troooooooop !")
INSERT INTO defis(id, citation) VALUES ( 35, "DAMN !")
INSERT INTO defis(id, citation) VALUES ( 36, "Nan mais pour moi ...")
INSERT INTO defis(id, citation) VALUES ( 37, "Ah ! y'a des olives par ici")
INSERT INTO defis(id, citation) VALUES ( 38, "Olive !")
INSERT INTO defis(id, citation) VALUES ( 39, "Ce soir, j'ai Switch")
INSERT INTO defis(id, citation) VALUES ( 40, "On est quel jooooouuuuuur ?!")
INSERT INTO defis(id, citation) VALUES ( 41, "SSBU chez moi ce soir ?")
INSERT INTO defis(id, citation) VALUES ( 42, "Pas ce soir, c'est Shabbat.")
INSERT INTO defis(id, citation) VALUES ( 43, "Je te fais un Revolut ?")
INSERT INTO defis(id, citation) VALUES ( 44, "Tu me fais un Revolut ?")
INSERT INTO defis(id, citation) VALUES ( 45, "Oh, mais c'est Rafabelle !")
INSERT INTO defis(id, citation) VALUES ( 46, "On dit pas qu'elle est bonne !")
INSERT INTO defis(id, citation) VALUES ( 47, "Vous êtes trop des choux !")
INSERT INTO defis(id, citation) VALUES ( 48, "Brondon !")
INSERT INTO defis(id, citation) VALUES ( 49, "Je suis une star d'UX !")
INSERT INTO defis(id, citation) VALUES ( 50, "Tu te calmes Remido !")
INSERT INTO defis(id, citation) VALUES ( 51, "Devinez qui j'ai trouvé ? La Ricaravane")
INSERT INTO defis(id, citation) VALUES ( 52, "Pas une grande semaine pour mardinema :(")
INSERT INTO defis(id, citation) VALUES ( 53, "On se retrouve en bas, on y va molo.")
INSERT INTO defis(id, citation) VALUES ( 54, "Jarrive dans une heure, je suis à Nogent")
INSERT INTO defis(id, citation) VALUES ( 55, "J'ai besoin de bitcher")
INSERT INTO defis(id, citation) VALUES ( 56, "Pour tenir la croissance en CA, faut tenir la croissance en effectif et pour l'instant ça fait que baisser, donc pour l'instant ça pue. Car on doit faire plus de CA avec moins de gens, donc plus de TACE")
INSERT INTO defis(id, citation) VALUES ( 57, "Des motivés pour faire Paris-Fontainebleau en trottinette ?")
INSERT INTO defis(id, citation) VALUES ( 58, "Un peu de violence pour rappeler certains principes, c'est comme ça que ça rentre,")
INSERT INTO defis(id, citation) VALUES ( 59, "Ah mais moi, j'aime bien quand les mecs viennent me voir.")
INSERT INTO defis(id, citation) VALUES ( 60, "Ooooh, trop mignons vos messages !")
INSERT INTO defis(id, citation) VALUES ( 61, "Nan mais moi ...")
INSERT INTO defis(id, citation) VALUES ( 62, "Il etait quand même archi beau gosse !")
INSERT INTO defis(id, citation) VALUES ( 63, "Senior Manager de mon cul !")
INSERT INTO defis(id, citation) VALUES ( 64, "Des shots !")
INSERT INTO defis(id, citation) VALUES ( 65, "Tournée de shots !")
INSERT INTO defis(id, citation) VALUES ( 66, "J'ai des horaires de sortie, je ne suis pas une femme libre.")
INSERT INTO defis(id, citation) VALUES ( 67, "La loi des deux R : un ricard et une rose, ça rend une femme heureuse.")
INSERT INTO defis(id, citation) VALUES ( 68, "Bon, soit on boit correctement, soit on y va !")
INSERT INTO defis(id, citation) VALUES ( 69, "Oh l'enfer !")
INSERT INTO defis(id, citation) VALUES ( 70, "Nan mais ce mec ...")
INSERT INTO defis(id, citation) VALUES ( 71, "On a pas 95 ans ...")
INSERT INTO defis(id, citation) VALUES ( 72, "Vas-y fonce !")
INSERT INTO defis(id, citation) VALUES ( 73, "Girl Power !")
INSERT INTO defis(id, citation) VALUES ( 74, "Team Laboure !")
INSERT INTO defis(id, citation) VALUES ( 75, "Je suis à Creteil Soleil ce WE.")
INSERT INTO defis(id, citation) VALUES ( 76, "C'est jamais assez chaud")
INSERT INTO defis(id, citation) VALUES ( 77, "Toi je t'aime bien !")
INSERT INTO defis(id, citation) VALUES ( 78, "Toi ..., je te kiffe !")
INSERT INTO defis(id, citation) VALUES ( 79, "Manager, c'est pas mettre des doigts.")
INSERT INTO defis(id, citation) VALUES ( 80, "Ouais, ça te fait marrer toi.")
INSERT INTO defis(id, citation) VALUES ( 81, "J'arrive dans 1h avec des tréteaux")
INSERT INTO defis(id, citation) VALUES ( 82, "Qui est dispo pour un déménagement, j'offre les bières.")
INSERT INTO defis(id, citation) VALUES ( 83, "Y a que moi qui ait envie de ken avec cette chaleur ?")
INSERT INTO defis(id, citation) VALUES ( 84, "Ils se sont toujours pas pécho ou quoi ? Je sens ce genre de truc ...")
INSERT INTO defis(id, citation) VALUES ( 85, "Nan je bois pas ce soir, je fais mon dry january !")
INSERT INTO defis(id, citation) VALUES ( 86, "Ah mais moi, je vais sur Grinder je peux trouver toute suite ...")
INSERT INTO defis(id, citation) VALUES ( 87, "Quand je suis triste, j'ai besoin de boire.")
INSERT INTO defis(id, citation) VALUES ( 88, "Je suis une vraie pute des langages.")
INSERT INTO defis(id, citation) VALUES ( 89, "Tiens ! Va au Kaddok t'acheter de l'alcool !")

INSERT INTO solution_citations VALUES(1, "CYG")
INSERT INTO solution_citations VALUES(2, "CYG")
INSERT INTO solution_citations VALUES(3, "CYG")
INSERT INTO solution_citations VALUES(4, "CYG")
INSERT INTO solution_citations VALUES(5, "CYG")
INSERT INTO solution_citations VALUES(6, "CYG")
INSERT INTO solution_citations VALUES(7, "CYG")
INSERT INTO solution_citations VALUES(8, "CYG")
INSERT INTO solution_citations VALUES(9, "RDO")
INSERT INTO solution_citations VALUES(10, "RDO")
INSERT INTO solution_citations VALUES(11, "RDO")
INSERT INTO solution_citations VALUES(12, "RDO")
INSERT INTO solution_citations VALUES(13, "RDO")
INSERT INTO solution_citations VALUES(14, "RDO")
INSERT INTO solution_citations VALUES(15, "RDO")
INSERT INTO solution_citations VALUES(16, "RDO")
INSERT INTO solution_citations VALUES(17, "RDO")
INSERT INTO solution_citations VALUES(18, "RDO")
INSERT INTO solution_citations VALUES(19, "BEJ")
INSERT INTO solution_citations VALUES(20, "BEJ")
INSERT INTO solution_citations VALUES(20, "BRM")
INSERT INTO solution_citations VALUES(21, "BEJ")
INSERT INTO solution_citations VALUES(22, "BEJ")
INSERT INTO solution_citations VALUES(23, "BEJ")
INSERT INTO solution_citations VALUES(24, "BEJ")
INSERT INTO solution_citations VALUES(25, "BEJ")
INSERT INTO solution_citations VALUES(26, "BEJ")
INSERT INTO solution_citations VALUES(26, "CYG")
INSERT INTO solution_citations VALUES(27, "BEJ")
INSERT INTO solution_citations VALUES(28, "BEJ")
INSERT INTO solution_citations VALUES(29, "BEJ")
INSERT INTO solution_citations VALUES(30, "BEJ")
INSERT INTO solution_citations VALUES(30, "BME")
INSERT INTO solution_citations VALUES(31, "BRM")
INSERT INTO solution_citations VALUES(32, "BRM")
INSERT INTO solution_citations VALUES(33, "BRM")
INSERT INTO solution_citations VALUES(34, "BRM")
INSERT INTO solution_citations VALUES(35, "BRM")
INSERT INTO solution_citations VALUES(36, "BRM")
INSERT INTO solution_citations VALUES(37, "BRM")
INSERT INTO solution_citations VALUES(38, "BRM")
INSERT INTO solution_citations VALUES(38, "CYG")
INSERT INTO solution_citations VALUES(39, "BRM")
INSERT INTO solution_citations VALUES(39, "CYG")
INSERT INTO solution_citations VALUES(40, "BRM")
INSERT INTO solution_citations VALUES(40, "BEJ")
INSERT INTO solution_citations VALUES(41, "DAS")
INSERT INTO solution_citations VALUES(42, "DAS")
INSERT INTO solution_citations VALUES(43, "DAS")
INSERT INTO solution_citations VALUES(44, "DAS")
INSERT INTO solution_citations VALUES(45, "LAAL")
INSERT INTO solution_citations VALUES(46, "LAAL")
INSERT INTO solution_citations VALUES(46, "CYG")
INSERT INTO solution_citations VALUES(47, "LAAL")
INSERT INTO solution_citations VALUES(48, "LAAL")
INSERT INTO solution_citations VALUES(49, "LAAL")
INSERT INTO solution_citations VALUES(50, "LAAL")
INSERT INTO solution_citations VALUES(51, "LAAL")
INSERT INTO solution_citations VALUES(52, "LAAL")
INSERT INTO solution_citations VALUES(53, "BME")
INSERT INTO solution_citations VALUES(53, "RDO")
INSERT INTO solution_citations VALUES(54, "BME")
INSERT INTO solution_citations VALUES(55, "BME")
INSERT INTO solution_citations VALUES(56, "BME")
INSERT INTO solution_citations VALUES(57, "BME")
INSERT INTO solution_citations VALUES(58, "BME")
INSERT INTO solution_citations VALUES(59, "RBO")
INSERT INTO solution_citations VALUES(60, "RBO")
INSERT INTO solution_citations VALUES(61, "RBO")
INSERT INTO solution_citations VALUES(62, "RBO")
INSERT INTO solution_citations VALUES(63, "MBI")
INSERT INTO solution_citations VALUES(64, "MBI")
INSERT INTO solution_citations VALUES(65, "MBI")
INSERT INTO solution_citations VALUES(66, "MBI")
INSERT INTO solution_citations VALUES(67, "MBI")
INSERT INTO solution_citations VALUES(67, "RDO")
INSERT INTO solution_citations VALUES(68, "MBI")
INSERT INTO solution_citations VALUES(69, "JDO")
INSERT INTO solution_citations VALUES(70, "JDO")
INSERT INTO solution_citations VALUES(71, "JDO")
INSERT INTO solution_citations VALUES(72, "JDO")
INSERT INTO solution_citations VALUES(73, "FAM")
INSERT INTO solution_citations VALUES(74, "FAM")
INSERT INTO solution_citations VALUES(75, "MEG")
INSERT INTO solution_citations VALUES(76, "MEG")
INSERT INTO solution_citations VALUES(77, "CEM")
INSERT INTO solution_citations VALUES(78, "CEM")
INSERT INTO solution_citations VALUES(79, "CEM")
INSERT INTO solution_citations VALUES(80, "CEM")
INSERT INTO solution_citations VALUES(81, "SLU")
INSERT INTO solution_citations VALUES(82, "SLU")
INSERT INTO solution_citations VALUES(83, "LJA")
INSERT INTO solution_citations VALUES(84, "LJA")
INSERT INTO solution_citations VALUES(85, "LJA")
INSERT INTO solution_citations VALUES(86, "CLI")
INSERT INTO solution_citations VALUES(87, "MID")
INSERT INTO solution_citations VALUES(88, "MID")
INSERT INTO solution_citations VALUES(89, "MID")
